name: king_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  connectivity_plus: ^7.1.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^10.3.0
  get: ^4.7.3
  go_router: ^17.2.3
  google_fonts: ^8.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logoo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logoo.png"
  adaptive_icon_background: "#ff001E40"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

